---
- hosts: frontend
  become: yes

  vars:
    frontend_build_path: "{{ lookup('env', 'FRONTEND_BUILD_PATH') }}"
    backend_private_ip: "{{ hostvars['backend'].ansible_host }}"

  roles:
    - web
