---
- hosts: frontend
  become: yes

  vars:
    frontend_build_path: ../frontend/dist

  tasks:
    - name: Set backend_private_ip var
      set_fact:
        backend_private_ip: "{{ hostvars['backend'].ansible_host }}"

  roles:
    - web
