---
- hosts: backend
  become: yes

  vars:
  rds_user: "{{ lookup('env', 'RDS_USER') }}"
  rds_password: "{{ lookup('env', 'RDS_PASSWORD') }}"
  rds_db: "{{ lookup('env', 'RDS_DB') }}"
  rds_endpoint: "{{ lookup('env', 'RDS_ENDPOINT') }}"


  roles:
    - backend
